// <auto-generated />
using LancheWeb.Data.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LancheWeb.Data.Migrations
{
    [DbContext(typeof(LancheContext))]
    partial class LancheContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LancheWeb.Models.Models.Ingrediente", b =>
                {
                    b.Property<int>("IngredienteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<int>("Quantidade");

                    b.Property<decimal>("Valor");

                    b.HasKey("IngredienteId");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("LancheWeb.Models.Models.IngredienteLanche", b =>
                {
                    b.Property<int>("IdLanche");

                    b.Property<int>("IdIngrediente");

                    b.Property<int>("Quantidade");

                    b.HasKey("IdLanche", "IdIngrediente");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("IngredienteLanche");
                });

            modelBuilder.Entity("LancheWeb.Models.Models.Lanche", b =>
                {
                    b.Property<int>("LancheId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("LancheId");

                    b.ToTable("Lanches");
                });

            modelBuilder.Entity("LancheWeb.Models.Models.IngredienteLanche", b =>
                {
                    b.HasOne("LancheWeb.Models.Models.Ingrediente", "Ingrediente")
                        .WithMany("IngredienteLanches")
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LancheWeb.Models.Models.Lanche", "Lanche")
                        .WithMany("IngredienteLanches")
                        .HasForeignKey("IdLanche")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
